//! General pasteboard history: privacy filter, SQLite FIFO, and search.
//!
//! History is opt-in (Settings default OFF). The expensive `pasteboardItems`
//! read happens only when `changeCount` moves. Polling is the caller's job —
//! piggyback the existing island cadence at ≤ 1 Hz; do not add a timer here.

use crate::database;
use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};

/// nspasteboard.org marker — password managers and secure fields.
pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
pub const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

pub const DEFAULT_HISTORY_CAP: u32 = 500;
#[cfg(target_os = "macos")]
const MAX_IMAGE_BYTES: usize = 1024 * 1024;

static SCREEN_LOCKED: AtomicBool = AtomicBool::new(false);
static LAST_CHANGE_COUNT: AtomicI64 = AtomicI64::new(i64::MIN);
static SUPPRESS_NEXT: AtomicBool = AtomicBool::new(false);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ClipboardKind {
    Text,
    Image,
    File,
}

impl ClipboardKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Text => "text",
            Self::Image => "image",
            Self::File => "file",
        }
    }

    fn parse(value: &str) -> Self {
        match value {
            "image" => Self::Image,
            "file" => Self::File,
            _ => Self::Text,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClipboardRecord {
    pub id: i64,
    pub kind: ClipboardKind,
    pub text: String,
    pub app_bundle_id: Option<String>,
    pub copied_at: i64,
    pub pinned: bool,
}

/// True when a pasteboard UTI is a privacy marker (or Apple's promised-file oddity).
pub fn is_private_type(uti: &str) -> bool {
    let uti = uti.trim();
    uti.eq_ignore_ascii_case(TRANSIENT_TYPE)
        || uti.eq_ignore_ascii_case(CONCEALED_TYPE)
        || uti.eq_ignore_ascii_case(AUTO_GENERATED_TYPE)
        || uti.eq_ignore_ascii_case("org.nspasteboard.concealedtype")
        || uti.contains("promised-file-content-type")
}

/// Skip the item when any declared type is a privacy marker.
pub fn should_skip_types<S: AsRef<str>>(types: &[S]) -> bool {
    types.iter().any(|t| is_private_type(t.as_ref()))
}

/// Frontmost-app heuristic used at copy time (the copier is not knowable).
pub fn is_excluded_app(bundle_id: Option<&str>, exclusions: &[String]) -> bool {
    let Some(bundle) = bundle_id.map(str::trim).filter(|s| !s.is_empty()) else {
        return false;
    };
    exclusions.iter().any(|ex| {
        let ex = ex.trim();
        !ex.is_empty() && ex.eq_ignore_ascii_case(bundle)
    })
}

pub fn set_screen_locked(locked: bool) {
    SCREEN_LOCKED.store(locked, Ordering::Relaxed);
}

pub fn screen_locked() -> bool {
    SCREEN_LOCKED.load(Ordering::Relaxed)
}

pub fn suppress_next_capture() {
    SUPPRESS_NEXT.store(true, Ordering::Relaxed);
}

/// Cheap `changeCount` snapshot. Returns `true` when the board moved since the
/// last call. Does not read pasteboard items.
pub fn change_count_moved() -> bool {
    if screen_locked() {
        return false;
    }
    let count = general_change_count();
    if count == i64::MIN {
        return false;
    }
    let last = LAST_CHANGE_COUNT.swap(count, Ordering::Relaxed);
    if last == i64::MIN || last == count {
        return false;
    }
    if SUPPRESS_NEXT.swap(false, Ordering::Relaxed) {
        return false;
    }
    true
}

pub fn recent(limit: u32) -> Vec<ClipboardRecord> {
    load_rows(
        "SELECT id, kind, text, app_bundle_id, copied_at, pinned
         FROM clipboard_items ORDER BY copied_at DESC, id DESC LIMIT ?1",
        rusqlite::params![limit.max(1) as i64],
    )
}

pub fn search(query: &str, limit: u32) -> Vec<ClipboardRecord> {
    let term = query.trim();
    if term.is_empty() {
        return recent(limit);
    }
    let like = format!("%{}%", escape_like(term));
    load_rows(
        "SELECT id, kind, text, app_bundle_id, copied_at, pinned
         FROM clipboard_items
         WHERE text LIKE ?1 ESCAPE '\\'
         ORDER BY copied_at DESC, id DESC LIMIT ?2",
        rusqlite::params![like, limit.max(1) as i64],
    )
}

pub fn insert_capture(
    kind: ClipboardKind,
    text: &str,
    image: Option<&[u8]>,
    app_bundle_id: Option<&str>,
    cap: u32,
) -> Result<bool, String> {
    let text = text.trim();
    if text.is_empty() && image.is_none() {
        return Ok(false);
    }
    let conn = database::get_connection().map_err(|e| e.to_string())?;
    if consecutive_duplicate(&conn, kind, text)? {
        return Ok(false);
    }
    let now = unix_now();
    conn.execute(
        "INSERT INTO clipboard_items (kind, text, image, app_bundle_id, copied_at, pinned)
         VALUES (?1, ?2, ?3, ?4, ?5, 0)",
        rusqlite::params![
            kind.as_str(),
            text,
            image,
            app_bundle_id,
            now,
        ],
    )
    .map_err(|e| e.to_string())?;
    trim_fifo(&conn, cap.max(1))?;
    Ok(true)
}

/// Read the general pasteboard (when history is on and `changeCount` moved).
pub fn capture_current(exclude_apps: &[String], cap: u32) -> bool {
    #[cfg(target_os = "macos")]
    {
        capture_macos(exclude_apps, cap)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = (exclude_apps, cap);
        false
    }
}

pub fn write_text(text: &str) -> bool {
    #[cfg(target_os = "macos")]
    {
        write_text_macos(text)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = text;
        false
    }
}

fn general_change_count() -> i64 {
    #[cfg(target_os = "macos")]
    {
        macos_change_count()
    }
    #[cfg(not(target_os = "macos"))]
    {
        i64::MIN
    }
}

fn escape_like(term: &str) -> String {
    let mut out = String::with_capacity(term.len());
    for c in term.chars() {
        if matches!(c, '%' | '_' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

fn unix_now() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

fn consecutive_duplicate(
    conn: &rusqlite::Connection,
    kind: ClipboardKind,
    text: &str,
) -> Result<bool, String> {
    let mut stmt = conn
        .prepare(
            "SELECT kind, text FROM clipboard_items ORDER BY id DESC LIMIT 1",
        )
        .map_err(|e| e.to_string())?;
    let row = stmt.query_row([], |row| {
        Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
    });
    match row {
        Ok((last_kind, last_text)) => {
            Ok(ClipboardKind::parse(&last_kind) == kind && last_text == text)
        }
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(false),
        Err(err) => Err(err.to_string()),
    }
}

fn trim_fifo(conn: &rusqlite::Connection, cap: u32) -> Result<(), String> {
    let count: i64 = conn
        .query_row("SELECT COUNT(*) FROM clipboard_items", [], |row| row.get(0))
        .map_err(|e| e.to_string())?;
    let overflow = count - cap as i64;
    if overflow <= 0 {
        return Ok(());
    }
    conn.execute(
        "DELETE FROM clipboard_items WHERE id IN (
            SELECT id FROM clipboard_items WHERE pinned = 0
            ORDER BY copied_at ASC, id ASC LIMIT ?1
        )",
        rusqlite::params![overflow],
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

fn load_rows(sql: &str, params: impl rusqlite::Params) -> Vec<ClipboardRecord> {
    let Ok(conn) = database::get_connection() else {
        return Vec::new();
    };
    let Ok(mut stmt) = conn.prepare(sql) else {
        return Vec::new();
    };
    stmt.query_map(params, |row| {
        Ok(ClipboardRecord {
            id: row.get(0)?,
            kind: ClipboardKind::parse(&row.get::<_, String>(1).unwrap_or_default()),
            text: row.get(2)?,
            app_bundle_id: row.get(3)?,
            copied_at: row.get(4)?,
            pinned: row.get::<_, i64>(5).unwrap_or(0) != 0,
        })
    })
    .ok()
    .into_iter()
    .flatten()
    .flatten()
    .collect()
}

#[cfg(target_os = "macos")]
fn macos_change_count() -> i64 {
    use objc2::runtime::AnyObject;
    use objc2::*;
    unsafe {
        let pb: *mut AnyObject = msg_send![class!(NSPasteboard), generalPasteboard];
        if pb.is_null() {
            return i64::MIN;
        }
        msg_send![pb, changeCount]
    }
}

#[cfg(target_os = "macos")]
fn capture_macos(exclude_apps: &[String], cap: u32) -> bool {
    use objc2::runtime::AnyObject;
    use objc2::*;
    unsafe {
        let pb: *mut AnyObject = msg_send![class!(NSPasteboard), generalPasteboard];
        if pb.is_null() {
            return false;
        }
        let types: *mut AnyObject = msg_send![pb, types];
        if types.is_null() {
            return false;
        }
        let type_count: usize = msg_send![types, count];
        let mut declared = Vec::with_capacity(type_count);
        for i in 0..type_count {
            let t: *mut AnyObject = msg_send![types, objectAtIndex: i];
            if let Some(s) = nsstring_to_rust(t) {
                declared.push(s);
            }
        }
        if should_skip_types(&declared) {
            return false;
        }
        let bundle = frontmost_bundle_id();
        if is_excluded_app(bundle.as_deref(), exclude_apps) {
            return false;
        }

        let text = pasteboard_string(pb, "public.utf8-plain-text")
            .or_else(|| pasteboard_string(pb, "public.utf16-plain-text"));
        let file = pasteboard_string(pb, "public.file-url");
        let image = pasteboard_data(pb, "public.png")
            .or_else(|| pasteboard_data(pb, "public.tiff"));

        if let Some(file) = file.filter(|s| !s.is_empty()) {
            let path = file_url_to_path(&file).unwrap_or(file);
            return insert_capture(ClipboardKind::File, &path, None, bundle.as_deref(), cap)
                .unwrap_or(false);
        }
        if let Some(bytes) = image.filter(|b| !b.is_empty() && b.len() <= MAX_IMAGE_BYTES) {
            let preview = text.as_deref().unwrap_or("[Image]");
            return insert_capture(
                ClipboardKind::Image,
                preview,
                Some(&bytes),
                bundle.as_deref(),
                cap,
            )
            .unwrap_or(false);
        }
        if let Some(text) = text.filter(|s| !s.trim().is_empty()) {
            return insert_capture(ClipboardKind::Text, &text, None, bundle.as_deref(), cap)
                .unwrap_or(false);
        }
        false
    }
}

#[cfg(target_os = "macos")]
fn write_text_macos(text: &str) -> bool {
    use objc2::runtime::AnyObject;
    use objc2::*;
    suppress_next_capture();
    unsafe {
        let pb: *mut AnyObject = msg_send![class!(NSPasteboard), generalPasteboard];
        if pb.is_null() {
            return false;
        }
        let _: i64 = msg_send![pb, clearContents];
        let ns: *mut AnyObject = rust_to_nsstring(text);
        if ns.is_null() {
            return false;
        }
        let ok: bool = msg_send![pb, setString: ns, forType: rust_to_nsstring("public.utf8-plain-text")];
        let count = macos_change_count();
        if count != i64::MIN {
            LAST_CHANGE_COUNT.store(count, Ordering::Relaxed);
        }
        ok
    }
}

#[cfg(target_os = "macos")]
unsafe fn pasteboard_string(pb: *mut objc2::runtime::AnyObject, uti: &str) -> Option<String> {
    use objc2::runtime::AnyObject;
    use objc2::*;
    let ty = rust_to_nsstring(uti);
    let s: *mut AnyObject = msg_send![pb, stringForType: ty];
    nsstring_to_rust(s)
}

#[cfg(target_os = "macos")]
unsafe fn pasteboard_data(pb: *mut objc2::runtime::AnyObject, uti: &str) -> Option<Vec<u8>> {
    use objc2::runtime::AnyObject;
    use objc2::*;
    let ty = rust_to_nsstring(uti);
    let data: *mut AnyObject = msg_send![pb, dataForType: ty];
    if data.is_null() {
        return None;
    }
    let len: usize = msg_send![data, length];
    if len == 0 {
        return None;
    }
    let bytes: *const u8 = msg_send![data, bytes];
    if bytes.is_null() {
        return None;
    }
    Some(std::slice::from_raw_parts(bytes, len).to_vec())
}

#[cfg(target_os = "macos")]
fn frontmost_bundle_id() -> Option<String> {
    use objc2::runtime::AnyObject;
    use objc2::*;
    unsafe {
        let ws: *mut AnyObject = msg_send![class!(NSWorkspace), sharedWorkspace];
        if ws.is_null() {
            return None;
        }
        let app: *mut AnyObject = msg_send![ws, frontmostApplication];
        if app.is_null() {
            return None;
        }
        let bundle: *mut AnyObject = msg_send![app, bundleIdentifier];
        nsstring_to_rust(bundle)
    }
}

#[cfg(target_os = "macos")]
fn file_url_to_path(url: &str) -> Option<String> {
    let parsed = url.strip_prefix("file://")?;
    let decoded = percent_decode(parsed);
    Some(decoded)
}

#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
fn percent_decode(input: &str) -> String {
    let bytes = input.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(v) = u8::from_str_radix(std::str::from_utf8(&bytes[i + 1..i + 3]).unwrap_or(""), 16)
            {
                out.push(v);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

#[cfg(target_os = "macos")]
fn rust_to_nsstring(s: &str) -> *mut objc2::runtime::AnyObject {
    use objc2::runtime::AnyObject;
    use objc2::*;
    unsafe {
        let ns: *mut AnyObject = msg_send![class!(NSString), alloc];
        msg_send![ns, initWithBytes: s.as_ptr(), length: s.len(), encoding: 4u64]
    }
}

#[cfg(target_os = "macos")]
fn nsstring_to_rust(s: *mut objc2::runtime::AnyObject) -> Option<String> {
    use objc2::*;
    if s.is_null() {
        return None;
    }
    unsafe {
        let cstr: *const i8 = msg_send![s, UTF8String];
        if cstr.is_null() {
            return None;
        }
        Some(std::ffi::CStr::from_ptr(cstr).to_string_lossy().into_owned())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn privacy_filter_skips_nspasteboard_markers() {
        assert!(is_private_type(TRANSIENT_TYPE));
        assert!(is_private_type(CONCEALED_TYPE));
        assert!(is_private_type(AUTO_GENERATED_TYPE));
        assert!(is_private_type("com.apple.pasteboard.promised-file-content-type"));
        assert!(!is_private_type("public.utf8-plain-text"));
        assert!(should_skip_types(&[
            "public.utf8-plain-text",
            CONCEALED_TYPE
        ]));
        assert!(!should_skip_types(&["public.utf8-plain-text", "public.png"]));
    }

    #[test]
    fn exclusion_list_is_case_insensitive() {
        let list = vec!["com.apple.Safari".into(), "com.1password.1password".into()];
        assert!(is_excluded_app(Some("com.apple.safari"), &list));
        assert!(is_excluded_app(Some("com.1password.1password"), &list));
        assert!(!is_excluded_app(Some("com.apple.TextEdit"), &list));
        assert!(!is_excluded_app(None, &list));
        assert!(!is_excluded_app(Some("  "), &list));
    }

    #[test]
    fn like_escape_treats_wildcards_as_literals() {
        assert_eq!(escape_like("100%_off"), r"100\%\_off");
        assert_eq!(escape_like(r"a\b"), r"a\\b");
    }
}
