#!/usr/bin/env bash
# Fail if tracked files contain AI-attribution comments or slop-AI filler.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Attribution / filler only. Product names in real comments are fine.
# Policy docs that quote the banned phrases are excluded from the scan.
created='created by[[:space:]]+(claude|chatgpt|copilot|cursor|grok|gemini|an[[:space:]]+ai)'
generated_by='generated by[[:space:]]+(claude|chatgpt|copilot|cursor|grok|gemini|an[[:space:]]+ai)'
generated_with='generated with[[:space:]]+(claude|chatgpt|copilot|cursor|grok|gemini)'
written='written by[[:space:]]+(claude|chatgpt|copilot|cursor|grok|gemini)'
trailer='co-authored-by:[[:space:]].*(claude|chatgpt|copilot|cursor|gemini|grok|openai)'

printf '%s\n' \
  '// Created by Claude Code' \
  'Generated by ChatGPT' \
  'Generated with Copilot' \
  'Written by Grok' \
  'Co-Authored-By: Cursor Agent <cursoragent@cursor.com>' \
  'as an AI' \
  "I'm an AI" \
  | grep -Eiq "$created|$generated_by|$generated_with|$written|$trailer|as an ai|i am an ai|i['’]m an ai" \
  || { echo "error: check-ai-comments pattern is broken" >&2; exit 1; }

if git grep -nI --untracked -E -i \
  -e "$created" \
  -e "$generated_by" \
  -e "$generated_with" \
  -e "$written" \
  -e "$trailer" \
  -e 'as an ai' \
  -e "i am an ai" \
  -e "i['’]m an ai" \
  -- . \
  ':!AGENTS.md' \
  ':!CONTRIBUTING.md' \
  ':!scripts/check-ai-comments.sh' \
  ':!Cargo.lock' \
  ':!docs' \
  ':!third_party' \
  ':!site/package-lock.json'
then
  echo "error: AI-attribution / slop comments are banned (see CONTRIBUTING.md)" >&2
  exit 1
fi
